### ISSUE TITLE
argmin 0.4.7 violates semantic versioning

### ISSUE THREAD

**Issue by vadixidav** [argmin-rs/argmin#135]
I just ran a `cargo install` install on https://github.com/rust-cv/cv/tree/main/vslam-sandbox. It seems that the new version of `argmin` released within the last hour broke the build, despite being labeled as semantically compatible.

It seems to be related to nalgebra support. Below is a resulting error (which did not occur in the previous v0.4.6, which I was building with earlier in the day):

```rust
error[E0277]: the trait bound `Matrix<f64, Const<6_usize>, Const<1_usize>, ArrayStorage<f64, 6_usize, 1_usize>>: ArgminAdd<Matrix<f64, Const<6_usize>, Const<1_usize>, ArrayStorage<f64, 6_usize, 1_usize>>, Matrix<f64, Const<6_usize>, Const<1_usize>, ArrayStorage<f64, 6_usize, 1_usize>>>` is not satisfied
  --> cv-optimize/src/single_view_optimizer.rs:22:43
   |
22 |     NelderMead::new().with_initial_params(variants)
   |                                           ^^^^^^^^ the trait `ArgminAdd<Matrix<f64, Const<6_usize>, Const<1_usize>, ArrayStorage<f64, 6_usize, 1_usize>>, Matrix<f64, Const<6_usize>, Const<1_usize>, ArrayStorage<f64, 6_usize, 1_usize>>>` is not implemented for `Matrix<f64, Const<6_usize>, Const<1_usize>, ArrayStorage<f64, 6_usize, 1_usize>>`
```

**Comment by stefan-k** [comment]
I have to admit that I don't follow semantic versioning **yet** because I still think that the library is conceptually and API-wise in a somewhat early stage and I have plans to experiment quite a bit in the near future. Therefore any version update may include breaking changes. 

Thanks though for pointing it out --- I really should mention this in the readme.

The only relevant change from 0.4.6 to 0.4.7 is the change from nalgebra 0.28 to 0.29. In order to make your code compile with argmin 0.4.7 I suppose you need to update nalgebra as well.

Apologies for any inconveniences this has caused!

**Comment by vadixidav** [comment]
> I have to admit that I don't follow semantic versioning **yet** because I still think that the library is conceptually and API-wise in a somewhat early stage and I have plans to experiment quite a bit in the near future. Therefore any version update may include breaking changes.
> 
> Thanks though for pointing it out --- I really should mention this in the readme.
> 
> The only relevant change from 0.4.6 to 0.4.7 is the change from nalgebra 0.28 to 0.29. In order to make your code compile with argmin 0.4.7 I suppose you need to update nalgebra as well.
> 
> Apologies for any inconveniences this has caused!

I understand your sentiment, but by default Cargo does perform these upgrades automatically when installing, and it is typically expected that crates follow the versioning scheme.

I would recommend that you bump the minor version (`major.minor.patch`) on every release if you plan to break compatibility. This will make things easier, since then downstream users wont get automatically bumped up to the next version. Even if it is compatible, you can simply just keep bumping the minor version every release, and you should get the same effect. You won't need to worry about whether it is compatible or not in that case.

**Comment by stefan-k** [comment]
I will be more careful not to violate semantic versioning with future releases starting from v0.5.0 (#172).
